services:
  mysql:
    image: mysql:8.0
    container_name: chat-bot
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - pgdata:/var/lib/mysql

volumes:
  pgdata:
